package com.wei.springboot.dao;

import com.wei.springboot.entity.TStudent;
import org.apache.ibatis.annotations.Select;

import java.util.List;

public interface TStudentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_student
     *
     * @mbg.generated Wed Aug 05 15:11:42 GMT+08:00 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_student
     *
     * @mbg.generated Wed Aug 05 15:11:42 GMT+08:00 2020
     */
    int insert(TStudent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_student
     *
     * @mbg.generated Wed Aug 05 15:11:42 GMT+08:00 2020
     */
    int insertSelective(TStudent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_student
     *
     * @mbg.generated Wed Aug 05 15:11:42 GMT+08:00 2020
     */
    @Select("select * from t_student where id = #{id}")
    TStudent selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_student
     *
     * @mbg.generated Wed Aug 05 15:11:42 GMT+08:00 2020
     */
    int updateByPrimaryKeySelective(TStudent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_student
     *
     * @mbg.generated Wed Aug 05 15:11:42 GMT+08:00 2020
     */
    int updateByPrimaryKey(TStudent record);

    List<TStudent> selectAllStudents();
}